export const actions = {
  TOGGLE_LOGIN: 'TOGGLE_LOGIN',
  CLOSE_AUTH_MODEL: 'CLOSE_AUTH_MODEL',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  GET_CART_TOTALS: 'GET_CART_TOTALS',
  INCREASE_CART_ITEM: 'INCREASE_CART_ITEM',
  DECREASE_CART_ITEM: 'DECREASE_CART_ITEM',
  CLEAR_CART: 'CLEAR_CART',
  TOGGLE_CART_MODEL: 'TOGGLE_CART_MODEL',
};
